version: '3'
services:
  composer:
    build: ./docker/phpcli
    volumes:
      - "$PWD:/usr/share/nginx"
    command: sh -c "cd /usr/share/nginx && composer install"
  web:
    image: nginx:latest
    ports:
      - "8189:80"
    depends_on:
      - "phpfpm"
    volumes:
      - "$PWD/docker/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD:/usr/share/nginx"
  phpfpm:
    build: ./docker/phpfpm
    depends_on:
      - composer
    volumes:
      - "$PWD:/usr/share/nginx"
      - "$PWD/docker/.env.docker:/usr/share/nginx/.env"
  mysql57:
    image: mysql:5.7
    ports:
      - "13396:3306"
    volumes:
      - ./docker/schemas:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=D31aida!2
